###### '''
Data Dictionary

Variable	Definition	Key
survival	Survival	0 = No, 1 = Yes
pclass	Ticket class	1 = 1st, 2 = 2nd, 3 = 3rd
sex	Sex	
Age	Age in years	
sibsp	# of siblings / spouses aboard the Titanic	
parch	# of parents / children aboard the Titanic	
ticket	Ticket number	
fare	Passenger fare	
cabin	Cabin number	
embarked	Port of Embarkation	C = Cherbourg, Q = Queenstown, S = Southampton
Variable Notes

pclass: A proxy for socio-economic status (SES)
1st = Upper
2nd = Middle
3rd = Lower

age: Age is fractional if less than 1. If the age is estimated, is it in the form of xx.5

sibsp: The dataset defines family relations in this way...
Sibling = brother, sister, stepbrother, stepsister
Spouse = husband, wife (mistresses and fiancés were ignored)

parch: The dataset defines family relations in this way...
Parent = mother, father
Child = daughter, son, stepdaughter, stepson
Some children travelled only with a nanny, therefore parch=0 for them.
'''

In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv("http://bit.ly/imdbratings")

In [3]:
movies.head()

star_rating                     title content_rating   genre  duration  \
0          9.3  The Shawshank Redemption              R   Crime       142   
1          9.2             The Godfather              R   Crime       175   
2          9.1    The Godfather: Part II              R   Crime       200   
3          9.0           The Dark Knight          PG-13  Action       152   
4          8.9              Pulp Fiction              R   Crime       154   

                                         actors_list  
0  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1    [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3  [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4  [u'John Travolta', u'Uma Thurman', u'Samuel L....

shape(movies)

In [5]:
movies.shape

(979, 6)

In [26]:
movies[(movies.duration >= 200) & (movies.content_rating == "R")]

star_rating                        title content_rating  genre  duration  \
2           9.1       The Godfather: Part II              R  Crime       200   
78          8.4  Once Upon a Time in America              R  Crime       229   

                                          actors_list  
2   [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
78  [u'Robert De Niro', u'James Woods', u'Elizabet...

In [13]:
movies.head()

star_rating                     title content_rating   genre  duration  \
0          9.3  The Shawshank Redemption              R   Crime       142   
1          9.2             The Godfather              R   Crime       175   
2          9.1    The Godfather: Part II              R   Crime       200   
3          9.0           The Dark Knight          PG-13  Action       152   
4          8.9              Pulp Fiction              R   Crime       154   

                                         actors_list  
0  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1    [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3  [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4  [u'John Travolta', u'Uma Thurman', u'Samuel L....

In [14]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 979 entries, 0 to 978
Data columns (total 6 columns):
star_rating       979 non-null float64
title             979 non-null object
content_rating    976 non-null object
genre             979 non-null object
duration          979 non-null int64
actors_list       979 non-null object
dtypes: float64(1), int64(1), object(4)
memory usage: 46.0+ KB


In [15]:
movies.describe()

star_rating    duration
count   979.000000  979.000000
mean      7.889785  120.979571
std       0.336069   26.218010
min       7.400000   64.000000
25%       7.600000  102.000000
50%       7.800000  117.000000
75%       8.100000  134.000000
max       9.300000  242.000000

In [16]:
import scikit-learn as sklearn

SyntaxError: invalid syntax (<ipython-input-16-9a5cb4c336c8>, line 1)

In [19]:
df = pd.DataFrame([['green', 'M', 10.1, 'class1'], ['red', 'L', 10.5, 'class2'], ['blue', 'XL', 15.3, 'class1']])

In [20]:
df.columns = ['color', 'size', 'price', 'class_lable']

In [21]:
df.head()

color size  price class_lable
0  green    M   10.1      class1
1    red    L   10.5      class2
2   blue   XL   15.3      class1

In [22]:
size_mapping = {'XL':3, 'L':2, 'M':1}

In [23]:
df['size'] = df['size'].map(size_mapping)

In [24]:
df.head()

color  size  price class_lable
0  green     1   10.1      class1
1    red     2   10.5      class2
2   blue     3   15.3      class1

In [27]:
from sklearn.datasets import load_iris

In [29]:
iris = load_iris()

In [30]:
type(iris)

sklearn.datasets.base.Bunch

In [32]:
iris.data.shape

(150, 4)

In [33]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [34]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [35]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='<U10')

In [36]:
X = iris.data

In [37]:
y = iris.target

In [44]:
print(iris.target.shape)
print(iris.data.shape)

(150,)
(150, 4)


# Step1 : import the class you plan to use

In [45]:
from sklearn.neighbors import KNeighborsClassifier

# Step2: Instatiate the estimator

In [99]:
knn = KNeighborsClassifier(n_neighbors=1)

In [100]:
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


# Step3: Fit the model with the data (aka "model training")

In [101]:
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

# Step4: Predict the response for a new observation 

In [102]:
X[0,]

array([ 5.1,  3.5,  1.4,  0.2])

In [103]:
knn.predict([X[0,], X[53,]])

array([0, 1])

In [104]:
def calculate_accuracy(X, y, model):
    error_count = 0
    count = 0;
    for x in X:
        y_pred = model.predict(x)
        if y_pred != y[count]:
            error_count = error_count + 1
        count = count + 1
    return error_count

# Using different values for K

In [105]:
knn5 = KNeighborsClassifier(n_neighbors=5)

In [106]:
knn5.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [107]:
knn5.predict([X[0,], X[53,], X[107,]])

array([0, 1, 2])

In [108]:
len(X)

150

In [109]:
knn5_errors = calculate_accuracy(X, y, knn5)

C:\Users\tony\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\tony\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\tony\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your da

In [110]:
model = knn
#def calculate_accuracy(X, y, model):
error_count = 0
count = 0;
for x in X:
    y_pred = model.predict(X[count,])
    if y_pred != y[count]:
        error_count = error_count + 1
    count = count + 1
    #return error_count

C:\Users\tony\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\tony\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\tony\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your da

C:\Users\tony\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\tony\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\tony\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your da

In [111]:
error_count

0

In [112]:
knn5_errors

5

# Using a different classification model

In [113]:
from sklearn.linear_model import LogisticRegression

In [114]:
logreg = LogisticRegression()

In [115]:
logreg.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [116]:
error = calculate_accuracy(X, y, logreg)

C:\Users\tony\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\tony\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\tony\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your da

In [117]:
error

6

## Estimate the likely perforemace of a model on out-of-sample data so we can chosse the best model

## Predicting the testing accuracy

In [123]:
y_pred_logreg = logreg.predict(X)

In [124]:
y_pred_knn5 = knn5.predict(X)

In [125]:
y_pred_knn = knn.predict(X)

In [126]:
from sklearn import metrics

In [127]:
print(metrics.accuracy_score(y, y_pred_logreg), metrics.accuracy_score(y, y_pred_knn5), metrics.accuracy_score(y, y_pred_knn))

0.96 0.966666666667 1.0


### Estimate the performance for out-of-sample data 

### Evaluation procedure #2: Train/Test split

In [139]:
from sklearn.cross_validation import train_test_split

In [156]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.4, random_state = 9)

In [157]:
logreg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [158]:
knn5.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [159]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [160]:
y_test_pred_logreg = logreg.predict(X_test)

In [161]:
y_test_pred_knn5 = knn5.predict(X_test)

In [162]:
y_test_pred_knn = knn.predict(X_test)

In [163]:
print(metrics.accuracy_score(y_test, y_test_pred_logreg),
      metrics.accuracy_score(y_test, y_test_pred_knn5),
      metrics.accuracy_score(y_test, y_test_pred_knn))

0.983333333333 0.983333333333 0.966666666667


### Tuning parameters